### PR TITLE
Change of symbol width

### PR DESCRIPTION
**Pull request by vsky279**
Thanks for your great work.
The code was not working initially for me. After playing around I was exploring other sources. According to this document https://pushstack.wordpress.com/somfy-rts-protocol/ I tried to change the symbol width to 604us. This made your code work for me.

### CODE REVIEW

**Comment by Nickduino** [comment]
Thanks for your comment!

Did you clock your official remote?
On the pushstack blog, you'll see a comment by Johannes who says using 640 µs instead of 604µs greatly improved his reception. The patent _US7860481 B2_ mentions 640 ("The synchronization pulse can be 4.8 ms in length and can be separated from the last preamble pulse by 640 μS") as well as 1280 ms per bits (check figure 3 of the patent).
The blog author himself says his 1208 value could well be a typo (for 12**80** µs).
us07860481-20101228-d00003

During my tests, I found it to work with 604 as well as 640.
Are you sure this is the only thing you changed to make it work for you?

If you want to automate your blinds, you might be interested in this repo to make them work with a Raspberry Pi:
https://github.com/Nickduino/Pi-Somfy

**Comment by vsky279** [comment]
You're welcome.

I did not do any modification to my original remote.
You are probably right. Now I'm able to control blinds with 640. 604 doesn't work now. There has to be some other issue as the control does not work for 100%.

My intention is to write a NodeMCU lua library for ESP8266 and do very similar things as you do in your Pi-Somfy project. So please close this PR.

I have another issue. Commands 0x2 and 0x4 do just one small movement. I can't figure out what is the command to let blinds go completely down or up. Apparently you don't experience this issue. Do you have any idea?

**Comment by Nickduino** [comment]
The protocol is pretty lenient with the timing, 604 vs 640 should not be a big issue anyway.

0x2 is UP and the blinds should go up until they receive the STOP 0x1 command.
Sure you're not in programming mode or something?

That's probably not related but are you emitting on the proper frenquency? (i.e. 433.**42** MHz)

**Comment by vsky279** [comment]
So today it works with both widths 640 and 604.

I am not in the programming mode. The Somfy remote works normally. It's always one step up and one step down.

I changed the resonator crystal to 433.32 MHz so I should be emitting on the right frequency. I also realised that 0x1 works as "my" button on the remote. I'm pretty confused about that.

**Comment by Nickduino** [comment]
433.**4**2.

"Stop" and "My" are the same (the "My" function appeared later in the protocol's life)

Check out this thread, you'll find a protocol decoder allowing you to see what your remote (and Arduino sketch) sends:
https://forum.arduino.cc/index.php?topic=208346.0

**Comment by vsky279** [comment]
Merci pour ce link. Je vais voir a je reviens si j'avance.

**Comment by vsky279** [comment]
Thanks for the great link. I'm able to decode now my original control. The data broadcast by the original control correspond to what I've been trying to send. But the the behavior is different (full up vs. only 1 step up). So emitted data can't really be the same and have to differ somewhere.

I think the difference is in Addit. Info that can be sent after the standard 56 bits of data (see [patent US8189620](https://www.google.ch/patents/US8189620)). 
schema

I have modified the sketch so it receives also the additional 3 bytes. But unfortunately I am not able to understand it. I don't know whether and how Somfy obfuscates it. The patent is not very specific in this area and different implementations are possible.

Do you have any experience with decoding/coding of the Addit. Info data?

**Comment by Nickduino** [comment]
No experience with the additional information at all.

But the patent (which I haven't fully read) tells you that after the normal 56 bits, you get:
- A 1 ;
- 23 more bits, including 4 bits for the checksum, which is calculated on either the second frame, or the whole.

With a bit of luck the additional information won't be obfuscated, so you should see similar bits when you press it a few times in a row (apart from the CKS2). If you don't, you might find inspiration in the way the pushtack blogger decrypted the obfuscation code.

Lastly...do you emulate your remote with my sketch or did you register your MCU as a **new** unit?

**Comment by vsky279** [comment]
I tried both - emulate my remote as well as register new unit. I'm playing more with the new unit.

Unfortunately it seems the data are obfuscated. This is just a small excerpt when pushing the down button:
image

I will try to decode it assuming that only 4 bits out of 23 bits should hopefully vary.

**Comment by Nickduino** [comment]
New unit is the best approach to avoid out-syncing your actual remote I believe.

When you press another button, does the first byte (the second nibble?) change?
If so, you _could_ assume it's the most important part, the command. And since it's not obfuscated itself, you might also assume the obfuscation (a XOR of every nibble?) is done on the additional information regardless of the content of the main frame.

But the bits change when you send the same command, so I'd say:
1. either the CKS2 is calculated on the whole frame and not just the additional information ;
2. or the remote is including a (random?) code every time it sends the same additional information.

Let's suppose we're in case 2:
If you send 0x842CF4 after a valid frame, does it work (lucky!)? If not, try de-obfuscating it and check if the additional information doesn't contain the rolling code of the main frame. If not, is it case 1?

But we're way out of my skill set here, have you tried dropping a comment on the pushtack blog?

**Comment by Nickduino** [comment]
It's nice your publishing a NodeMCU version under the MIT licence, Lukas but I think it would be worth mentioning you based it on my job.
I'd really appreciate to see a link to my repository [here](https://github.com/vsky279/nodemcu-firmware/blob/somfy/app/modules/somfy.c).

Regards,
   Nick

**Comment by vsky279** [comment]
You're welcome ([https://github.com/vsky279/nodemcu-firmware/blob/somfy/app/modules/somfy.c](https://github.com/vsky279/nodemcu-firmware/blob/somfy/app/modules/somfy.c))

**Comment by Nickduino** [comment]
Thanks man!

I see your avatar is a plane dash...do you have a PPL?
I'm currently reading a lot about the Gaz'aile, I might take the plunge in a near future...

**Comment by vsky279** [comment]
:+1: No PPL, just GLD license..

**Comment by rgr101** [comment]
Hey Nick, hey Lukas, 

I'm very happy to having found your approaches of controlling Somfy RTS. 

Congrats! Great job!

As I have to control 23 blinds in total (different types but all Somfy RTS) in my house, 
I already have built a arduino-tapped-5-channel-original-Somfy-RTS control
(see also http://somfy-domotica.blogspot.de/), running a hard coded timer program 
which is running very well since several years, but as you can imagine controlling 23 blinds grouped in 5 channels done by hard coded timers isn't that nice and flexible:
Every time we are going to vacation, I have to change the timer values and re-flash the arduino before...

So, I already started with a similar new approach by tapping a 16-channel Somfy remote to an ESP8266/Lua. Hardware is already done and basic Lua code (controlling the remote by a Loxone mini server via UDP or TCP) is working well...

But as I now recognized that you guys have already solved the protocol emulation, I hope to get rid of hardware-tapping (and still only 16 channels then...) but doing the "job" directly. 

My goals are
- to control each single blind (direct up/down on demand -> 23 channels at minimum) 
  by Loxone and
- to set up a flexible / intelligent (e.g. sunset driven etc) set of timers for single or grouped blinds (not yet decided if in the Loxone or controller layer, as Loxone scripting maybe isn't the best choice...)

Now my questions to you guys :) :
- Is your protocol emulation(s) already robust and stable for running "in production"?
- Do you know the address space used by the original Somfy remotes /  
  which address space should be used to avoid address conflicts with my 23 installed (and still in use) Somfy remotes?
- Personally, I like the nodemcu approach very much as it offers an very easy access by other layers (like Loxone etc). But also I could imagine the Arduino approach - maybe ported to an ESP8266 on Arduino-firmware?

@Lukas: Is it correct that you are running the esp8266 still on the nodemcu/lua firmware and embed the somfy-driver as binary c-module? So, I could add some app logic (as e.g. intelligent timer programs) in the lua layer?
I'm also wondering if the run duration of a somfy sendcommand within the somfy-driver isn't critical to the nodemcu event handling? 

@Nick: Can you imagine to port your Arduino code on the ESP hardware (esp. because of the critical timing stuff of the protocol?
- so, what do you think would be the more robust and/or easier approach? 

Could you assist me a little bit in setting up the proper environment?
(as I'm not used in flashing nodemcu firmware etc. ...)  That's is surely OT, so I would be very happy to receive your PI - see email address in my profile :)

Thanks very much in advance!

Renato

**Comment by Nickduino** [comment]
Hi Renato and please forgive me for the delay,

Would "my" implementation of the Somfy RTS protocol allow you to control your blinds without any hardware tap? Yes!
Is it stable and working? Yes!

I do not know the address space used by Somfy. Likelihood you'll randomly use one of yours is crazy low in my opinion. If you really want to be meticulous, you can build (or find on the net) a **decoder**, which will tell you what your current remote values are.

About the ESP8266, I used it only once with the Arduino IDE to make a WiFi thermometer so I won't give you much info, I'm no specialist at all. I assume that porting the code wouldn't be an issue but I won't do it as I really don't have any need for it (and very few skills).
When you say ESP would be better because of the critical timing: the receivers are very tolerant, any symbol length that is remotely close to 640 µs is good enough.

One thing that might interest you, since you speak about intelligently driving your blinds is my **Python** version:
https://github.com/Nickduino/Pi-Somfy
I open them at 8AM and close them at sunset but you can imagine any scenario: open when it's cold inside and sunny and close when it's raining and your not home...

**Comment by rgr101** [comment]
Hi Nick, 

many thanks for your comments!

I am a relative newbie with the ESP; the only thing I made with it so far was the RTS tapping and LUA smaple coding for the TCP-Wifi communication Loxone-ESP-RTS... (which was REALLY easy) 

So, I believe next task for me will be to flashing the ESP with the Arduino IDE and porting your Somfy_Remote on it - I will give an update as soon as I've found some time... ;)

Ah and btw grabbing an RF transmitter and changingits frequency (I indeed have seen a chinese supplier on ebay who is delivering 433.42M TO39 resonators for little money)

Your Python version looks also very interesting, but unfortunately, I have ZERO experience with the Rasp-PI nor Python so far...

If you like I can provide you my Arduino code of my 5-channel tapped-remote :) 
In fact it's hard coded but quite flexible by providing multiple timers... - maybe this will a basis for my "new approach" with your untapped remote and more intelligence... :-)

**Comment by Nickduino** [comment]
All that very easy LUA thing, I didn't get one word of it :D

The 433.42 MHz crystals are an absolute necessity. Be careful when desoldering the old one.

Python: all very easy. What was less easy, was using a C daemon to build and send the frame but I've done it and you can use it as is.

I think you shouldn't rely on timers only but get the sunset of your location every day to decide when to close the blinds. To put some meaning in the "smart" of "smart home".

I'm closing the request since it doesn't make sense anymore, not sure if it allows you to reply. If not, you can still open a new thread.

**Comment by vsky279** [comment]
Hi Renato, I'm sorry I have some busy period. I will come back to you soon. Lukas

**Comment by rgr101** [comment]
Hi Lukas, no worries…!

**Comment by vsky279** [comment]
Hi Renato, 

I'm glad you gave me motivation to finalize the work on the NodeMCU lua Somfy driver.
Please have a look on the [documentation](https://github.com/vsky279/nodemcu-firmware/blob/somfy/docs/en/modules/somfy.md) of my module including a more sophisticated example.

The module is now probably ready to be pushed in the official NodeMCU Lua. Still I'm a bit worried that it won't be accepted as the number of users would be very limited.

As for your question relating the event handling - the driver is fully asynchronous so it is not blocking ESP8266 critical routines. It is using hardware timer and therefore not compatible with other NodeMCU modules using the hardware timer, i.e. `sigma delta`, `pcm`, `perf`, or `pwm` modules. Everything is event driven which allows elegant command chaining. Please refer to the [example](https://github.com/vsky279/nodemcu-firmware/blob/somfy/lua_examples/somfy.lua).

I use a bit more enhanced code then in the example to control my blinds. I close and open them with civil twilight. I am also opening them with strong wind (another ESP8266 provides information about the wind speed and direction). The operation is very reliable.

**Comment by rgr101** [comment]
Hi Lukas, 
you're very welcome ;-)

Sounds good. Now I'm completely confused how to proceed: both approaches, the Arduino and the Lua, sound great! At the end of the day, I must decide where I'm feeling more comfortable with (As I'm not a virtuous hacker, I should better keep the things rather simple...)

Just for understanding: 
- In the doc you refer to 433.**3**2 Mhz - I thought it must be 433.42?
  btw - have you experience with the range of the RF? today, I am controlling the complete house 
  (3 concrete floors) 
- I can't follow the behavior of your blinds by 2 or 16 repeats - but maybe my blinds are different (using the original Telis RTS remote, my blinds do a full close on pressing the down button just once and only stop after pressing the my/stop button; and 'emulating' your logic by e.g. pressing the down button twice doesn't stop the blind)? Or is there an additional, hidden function within the somfy protocol?
- as far as I understand the callback mechanism, the wait() function is called after the completion of the sendcommand(), so after having repeated sending the RTS code 2 or 16 times in your sample, right? Or will be waited for 100 or 300 ms after each sending of the RTS code?
- for the initial definition of the blinds I can easily edit a somfy.cfg file by an usual editor, right?
  (do _you_ have a suggestion for an good address space to use, as I have 23 Telis remotes in use and want to avoid address conflicts...)
- so, if you succeed in pushing the somfy module in the official nodemcu firmware, I just need to grab it from the official sources, right? And as long as that didn't happen, you provide an alternative, unofficial firmware in your branch I could use?

Actually, I'm waiting for some deliveries of RF modules and 433.42 resonators (for re-soldering) from China, so it will still take some time if I can realize the hardware...
but in the meantime I'd really love to proceed at least with the software part

Kind regards and sorry for any stupid questions :-) 
Renato

**Comment by Nickduino** [comment]
You can hardwire a remote to use it just as the antenna.

**Comment by rgr101** [comment]
great idea, thx!!

**Comment by Nickduino** [comment]
As an emitter, sorry.

**Comment by vsky279** [comment]
> In the doc you refer to 433.32 Mhz - I thought it must be 433.42?

That is a mistake. Corrected now.

> btw - have you experience with the range of the RF? today, I am controlling the complete house 
> (3 concrete floors)

This is my ESP8266 Somfy control. You can see the the antenna. Actually the range is an issue. The control does not work reliably if the box is closed. Also I cannot place it whenever I need it. I need to work on this issue.


> I can't follow the behavior of your blinds by 2 or 16 repeats - but maybe my blinds are different (using the original Telis RTS remote, my blinds do a full close on pressing the down button just once and only stop after pressing the my/stop button; and 'emulating' your logic by e.g. pressing the down button twice doesn't stop the blind)? Or is there an additional, hidden function within the somfy protocol?

My original remote is [TELIS 4 MODULIS RTS](https://www.somfy.co.uk/products/1810765/telis-4-modulis-rts). This remote is working with the additional info part of the frame as discussed above. I did not manage to decode and replicate this. When I send the `somfy.DOWN` command, repeating the frame twice (which should be the standard) the blinds go only 1 step down. This corresponds to the movement of the wheel on the original remote. The down button on the original remote sends also `somfy.DOWN` command but the additional info is different and this makes the blinds go full down. Fortunately I realized that repeating the frame 16 times makes the blinds go fully down.

> as far as I understand the callback mechanism, the wait() function is called after the completion of the sendcommand(), so after having repeated sending the RTS code 2 or 16 times in your sample, right? Or will be waited for 100 or 300 ms after each sending of the RTS code?

Your understanding is correct. I transmit the frame the specified number of times and then I wait for given period of time to ensure some spacing from next command.

> for the initial definition of the blinds I can easily edit a somfy.cfg file by an usual editor, right?
> (do you have a suggestion for an good address space to use, as I have 23 Telis remotes in use and want to avoid address conflicts...)

Yes, somfy.cfg is a simple CJSON test file. 

I have no suggestion for the address space. But as it is 24 bits large the chance that you have an address conflict is very low. If you choose by chance the same address you won't have correct rolling code (assuming you start from 1) so you should not be able even to register.

> so, if you succeed in pushing the somfy module in the official nodemcu firmware, I just need to grab it from the official sources, right? And as long as that didn't happen, you provide an alternative, unofficial firmware in your branch I could use?

If it is pushed to https://github.com/nodemcu/nodemcu-firmware then you will be able to compile from this source. After some time it should also appear on https://nodemcu-build.com/ so you would be able to download your custom build.

If it's not merged you would still be able to use the original branch (and be up-to-date), you would just add the `somfy.c` file and modify `user_modules.h` by adding `#define LUA_USE_MODULES_SOMFY`. This can be done by creating a pull request from my branch to your branch or adding the file manually (anyway I'm not a GitHub expert).

**Comment by Nickduino** [comment]
About the range issues, I solved them by shielding the emitter from the rest of the electronic stuff.

The bottom of a tin can soldered to ground.

**Comment by vsky279** [comment]
Sounds interesting. I will shield the ESP8266 ESP-01 that I use. It would be great if it solved my range issues.

**Comment by rgr101** [comment]
> My original remote is TELIS 4 MODULIS RTS
> Ah I see. So, I believe you have more sophisticated blinds... 
> I'm using only the "ordinary" Telis 1 (or 4 or 16) RTS, as I am controlling mainly my roller blinds (but also some venetian and canvas blinds; but all only simply doing up / stop (/MY) / down)...

About the range issues, I'm confident you're using an adequate (lambda/4) antenna length - (sry for asking, but sometimes the easiest things are not considered...) ? But anyway; maybe there are some unnoticed reflections (that could impact the "real" antenna length and be solved by shielding like Nick did) ?!?

**Comment by vsky279** [comment]
Hi Renato,

The somfy module should be merged ([PR 1521](https://github.com/nodemcu/nodemcu-firmware/pull/1521)) soon in the official dev branch of NodeMCU Lua.
Few days after it should appear also on  http://nodemcu-build.com/.

I hope you will give it a try :-)

**Comment by rgr101** [comment]
Sounds great! 

Today my brand new wemos d1 mini pro boards arrived from China - but I still have to wait for the RF modules and resonators (and some time for building ;) )...

KR
Renato

**Comment by vsky279** [comment]
Hi guys, my antenna problems have been solved by using a simple 433MHz antenna sold on ebay. No shielding needed.

**Comment by rgr101** [comment]
Hey guys, 
no idea if this reaches you - as the issue is already closed...
Anyway - just wanted to drop you an "alive" ticker after more than a year silence...

In the meantime, I finally succeeded in gathering some sample 433.42 resonators from a reliable supplier after my first approach didn't work out repeatedly...
Now, they are pushing me by weekly asking when I'm planning to finally entering into mass production - so feel free to ask me if you need 10000+ quantities :D 

So, I hope to find time to re-enter into my Somfy project soon. After having made some first steps with the NodeMCU board, I have to admit that I'm feeling more comfortable with a compiled (Arduino IDE) code rather than LUA (probably because I know it better from other projects...).

Besides that, I'm always thinking about an adequate placement of the Somfy part in a general  context, so my idea is to realizing a "Somfy binding" for Eclipse Smarthome/openHAB - to gain the maximum openness for any present and future smarthome environment, focussing just on a gateway functionality on the actor layer and leave any sophisticated controlling to the app layer of the user's choices smarthome...

What do you think?

Cheers!
Renato

**Comment by Nickduino** [comment]
Glad you found your parts and have the code working.

As for the rest, I can't help you as I haven't implemented that but I wish you the best!

**Pull request closed without merging**
